#include "fast_arithmetics_25519.h"

/*
    Define power on finite field of size 2^255-19.
*/

// ============================ DEFINE SUB-FUNCTIONS ============================

#define POW_STEP(limb_no, x, y, out)                \
    if (y.limbs[limb_no] & 0x1)                     \
        mul25519(out, out, &x);                     \
    sqr25519(&x, &x);                               \
    y.limbs[limb_no] >>= 1;


// ============================ POWER IN GF(2^255-19) ============================
void pow25519(Int25519 *out, Int25519 *x, Int25519 *y)
{
    Int25519 _x;
    _x.limbs[0] = x->limbs[0];
    _x.limbs[1] = x->limbs[1];
    _x.limbs[2] = x->limbs[2];
    _x.limbs[3] = x->limbs[3];
    _x.limbs[4] = x->limbs[4];

    Int25519 _y;
    _y.limbs[0] = y->limbs[0];
    _y.limbs[1] = y->limbs[1];
    _y.limbs[2] = y->limbs[2];
    _y.limbs[3] = y->limbs[3];
    _y.limbs[4] = y->limbs[4];

    out->limbs[0] = 1;
    out->limbs[1] = 0;
    out->limbs[2] = 0;
    out->limbs[3] = 0;
    out->limbs[4] = 0;

    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(0, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(1, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(2, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(3, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);
    POW_STEP(4, _x, _y, out);

}